name: Compilar APK Android

on:
  push:
    branches: [ main ]
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    name: Gerar APK
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
      - run: npm install
      - uses: actions/setup-java@v4
        with:
          distribution: "temurin"
          java-version: "17"
      - run: npx cap sync android
      - run: |
          sed -i -e "s/\r$//" android/gradlew
          chmod +x android/gradlew
      - run: cd android && ./gradlew assembleDebug --stacktrace
      - uses: actions/upload-artifact@v4
        with:
          name: Arena-Limoeiro-APK
          path: android/app/build/outputs/apk/debug/app-debug.apk
      - uses: softprops/action-gh-release@v2
        with:
          tag_name: apk-v${{ github.run_number }}
          name: "Arena Limoeiro APK - Versão ${{ github.run_number }}"
          files: android/app/build/outputs/apk/debug/app-debug.apk
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
